# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

sudo: required

services:
  - redis-server

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

# NOTE: libhiredis-dev is for RedisHeartbeat until I get linking working
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_aptget libhiredis-dev
  - ./travis-tool.sh github_package gaborcsardi/progress
  - ./travis-tool.sh github_package ropensci/RedisAPI
  - ./travis-tool.sh github_package richfitz/redux
  - ./travis-tool.sh github_package richfitz/RedisHeartbeat
  - ./travis-tool.sh github_package richfitz/storr
  - ./travis-tool.sh github_package richfitz/ids

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:hY2eBCaH3bbsvNwlWwOfFdfr
